[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts" , "@octant-v2-core/src=lib/octant-v2-core/src"]
optimizer = true
optimizer_runs = 50
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
